# This file was generated by GoReleaser. DO NOT EDIT.
cask "genie" do
  desc "AI-powered coding assistant with CLI and TUI interfaces"
  homepage "https://github.com/kcaldas/genie"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genie"

  on_macos do
    on_intel do
      url "https://github.com/kcaldas/genie/releases/download/v0.1.7/genie_0.1.7_darwin_amd64.tar.gz"
      sha256 "370224f5f1e3ac5f3c79d7c4b41dc14619a3db4000cb4865408d9d9238b868e4"
    end
    on_arm do
      url "https://github.com/kcaldas/genie/releases/download/v0.1.7/genie_0.1.7_darwin_arm64.tar.gz"
      sha256 "a4ff09414c8783b85d76d0d9f82a67b4df2d47c4e50e1b19d3afdba7406bb219"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kcaldas/genie/releases/download/v0.1.7/genie_0.1.7_linux_amd64.tar.gz"
      sha256 "efbacb9eea4864d3de525433a19d14ed0d0f5383e171beb86345204f4f536cb2"
    end
    on_arm do
      url "https://github.com/kcaldas/genie/releases/download/v0.1.7/genie_0.1.7_linux_arm64.tar.gz"
      sha256 "0ccc29dde88762601c830b9125ea1d2f5765fe6bc6adc47cc4792727c0863554"
    end
  end

  # No zap stanza required
end
