# This file was generated by GoReleaser. DO NOT EDIT.
cask "genie" do
  name "genie"
  desc "AI-powered coding assistant with CLI and TUI interfaces"
  homepage "https://github.com/kcaldas/genie"
  version "0.2.10-beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genie"

  on_macos do
    on_intel do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_darwin_amd64.tar.gz"
      sha256 "99ef497de0b464fad331cc600fd613479419cc6716f82be0bab8d17bcaae68ee"
    end
    on_arm do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_darwin_arm64.tar.gz"
      sha256 "6df17eee7dd592317f278c00bfec6a13ab80962626c65062eead4bb56502b32e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_linux_amd64.tar.gz"
      sha256 "e1c1b44c79ce0259d0eb6ca95f7b4915d091afb84dd2b905fd3630148196719c"
    end
    on_arm do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_linux_arm64.tar.gz"
      sha256 "e39f4363fc8f4f2c305dc7b5f4766a183dd382fde8e246663184ba98c008369a"
    end
  end

  # No zap stanza required
end
