# This file was generated by GoReleaser. DO NOT EDIT.
cask "genie" do
  name "genie"
  desc "AI-powered coding assistant with CLI and TUI interfaces"
  homepage "https://github.com/kcaldas/genie"
  version "0.2.9-beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genie"

  on_macos do
    on_intel do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_darwin_amd64.tar.gz"
      sha256 "e713a5675b4e0184f8d5fa2b3d581f9fe3e5855e90c8e0e93757fb09d1500a73"
    end
    on_arm do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_darwin_arm64.tar.gz"
      sha256 "90d536d284f733c27cd5788bff5173440040e986b0f12844df7f0189d80aaedc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_linux_amd64.tar.gz"
      sha256 "be37e1df1320d766e43140ff5048e8498431866317a68c810c05821df9f7f9f9"
    end
    on_arm do
      url "https://github.com/kcaldas/genie/releases/download/v#{version}/genie_#{version}_linux_arm64.tar.gz"
      sha256 "8f8e8fee31ea2acba94c5eaca804a5337e0cfd16f93f41ce30a0c9800ed00efe"
    end
  end

  # No zap stanza required
end
